### ISSUE TITLE
Boater’s Atlas gone?

### ISSUE THREAD

**Issue by bergie** [itemir/signalk-speedtest#1]
Is this service now dead? If so, that’s a shame. Was quite useful when planning remote working locations.

**Comment by itemir** [comment]
Hey @bergie , yes I disabled it for a few reasons:
1. It wasn't really clear to me anyone was actually using it. But now you are the second person who asked for it.
2. Plugin stopped working with SignalK v2 upgrade (speedtest npm package stopped working) and would require quite a bit of digging to figure out what was happening. But we practically stopped logging speeds for a while.
3. Last but not least, at least in the US, Starlink replaced almost all remote connectivity. So having Starlink speedtests from wherever was not being very useful since location doesn't really matter until you go beyond really north.

I kept the DB logs somewhere. Let me have a look, maybe I can put the available data as a json dump.

**Comment by bergie** [comment]
Thanks for the status update! Here in Europe it is still a lot better to use LTE than Starlink (typically 20€ vs. ~100€ per month, not to mention the difference in power usage). So we were actually using this service quite a bit to figure out the best anchoring spots.

The DB dump could be useful, we could maybe figure out some low-cost way to revive the service.

**Comment by itemir** [comment]
Ok, thanks, this is useful. Cost was not really a factor here as the servers are already running with or without boatersatlas, it doesn't add that much load. 

I just brought the site back from source code repo and database backups. It should be up now. Can you test if the uploads work? And a PR is welcome to ensure the plugin still works with later versions of SignalK and Node.js, I no longer use it myself.

**Comment by bergie** [comment]
Thanks! We’re in a place that’s quite well covered already by data, but I’ll have a look at what the plugin is up to.

**Comment by bergie** [comment]
We anchored last night in a place we’ve never anchored in before, and it has now appeared on the map. So seems to work! SK server 2.2.0

![IMG_1002](https://github.com/itemir/signalk-speedtest/assets/3346/1ddfe09b-cbc1-4db5-9bc4-61b7c0e67b1f)
